docker-images:
  - name: basic-image
    from: javierbrea/node-headless-chrome:1.0.0
    add:
      - package.json
      - npm-shrinkwrap.json
    expose:
      - 3000
    install: test/docker/install
docker-services:
  - name: service
    build: basic-image
    bind:
      - lib
      - test
      - index.js
  - name: test
    build: basic-image
    bind:
      - lib
      - test
      - index.js
    depends_on:
      - service
suites:
  unit: 
    - name: unit
      test:
        specs: test/unit
      coverage:
        config:
          dir: .coverage/unit
  integration:
    - name: built-in-api
      services:
        - docker-service: service
          exit_after: 20000
          commands:
            pre-local: test/services/commands/local/clean-shared
            local: test/services/app/start.js --name=service --path=.test
            docker: test/services/app/start.js --name=service --path=/app/.shared --host=service
      test: 
        docker-service: test
        wait-for: service:3000
        specs: test/integration/built-in-api
      coverage:
        from: service
    - name: tracer
      docker-compose-down: true
      services:
        - docker-service: service
          commands:
            local: test/services/commands/local/log-level-warn
            docker: test/services/commands/docker/log-level-warn
      test: 
        docker-service: test
        wait-for: service:3000
        specs: test/integration/tracer
      coverage:
        enabled: false
  end-to-end:
    - name: web-ui
      services:
        - docker-service: service
          commands:
#           local: test/end-to-end/web-ui/basic-service/start-local
            docker: test/services/commands/docker/basic-start
      test: 
        docker-service: test
        wait-for: service:3000
        specs: test/end-to-end/web-ui
