docker-images:
  - name: basic-image
    from: javierbrea/node-headless-chrome:1.0.0
    add:
      - package.json
#      - npm-shrinkwrap.json
    expose:
      - 3000
    install: test/docker/install
docker-containers:
  - name: service
    build: basic-image
    bind:
      - lib
      - test
      - index.js
  - name: test
    build: basic-image
    bind:
      - lib
      - test
      - index.js
    depends_on:
      - service
suites:
  unit: 
    - name: unit
      test:
        specs: test/unit
      coverage:
        config:
          dir: .coverage/unit
  integration:
    - name: built-in-api
      services:
        - name: service
          docker: 
            container: service
            command: test/services/app/start.js --name=service --path=/app/.shared --host=service
            exit_after: 10000
          local:
            command: test/services/app/start.js --name=service --path=.test
      test:
        specs: test/integration/built-in-api
        docker:
          container: test
          wait-for: service:3000
        local:
          wait-for: tcp:localhost:3000
      coverage:
        from: service
    - name: tracer
      before:
        docker:
          down-volumes: true
        local:
          command: test/services/commands/local/clean
      services:
        - name: service
          docker:
            container: service
            command: test/services/commands/docker/log-level-warn
          local:
            command: test/services/commands/local/log-level-warn
      test:
        specs: test/integration/tracer
        docker:
          container: test
          wait-for: service:3000
        local:
          wait-for: tcp:localhost:3000
      coverage:
        enabled: false
  end-to-end:
    - name: web-ui
      services:
        - name: service
          docker:
            container: service
            command: test/services/commands/docker/basic-start
          local:
            command: test/services/commands/local/basic-start
      test:
        specs: test/end-to-end/web-ui
        docker: 
          container: test
          wait-for: service:3000
        local:
          wait-for: tcp:localhost:3000
