docker-images:
  - name: basic-image
    from: node:8.9.4
    add:
      - package.json
      - npm-shrinkwrap.json
      - old-test\integration///built-in-api/builtInApi.specs.js
      - old-test\integration///tracer
    expose:
      - 3000
    install: test/docker/basic-image/install
docker-services:
  - name: basic-service
    build: 
      context: basic-image
    bind:
      - lib
      - test
  - name: basic-test
    build:
      context: basic-image
    bind:
      - lib
      - test
      - node_modules
      - index.js
    depends_on:
      - basic-service
test:
  unit: test/unit
  integration:
    - name: built-in-api
      docker-compose-down: true
      services:
        - docker-service: basic-service
          commands:
            local: test/integration/built-in-api/basic-service/start-local
            docker: test/docker/command-example-1
      test: 
        docker-service: basic-test
        specs: test/unit
  end-to-end:
    - name: web-ui
      services:
        - docker-service: basic-service
          commands:
            local: test/end-to-end/web-ui/basic-service/start-local
            docker: test/docker/command-example2
      test: 
        docker-service: basic-test
        specs: test/unit
