language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"
    - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "domapic"
    token:
      secure: "$SONAR_TOKEN"
    branches:
      - master
      - fix-quality-tools

script:
  - npm test
  - npm run coveralls
  - sonar-scanner
