language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
addons:
  sonarcloud:
    organization: "domapic" # the key of the org you chose at step #3
    token:
      secure: SONAR_TOKEN
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
